---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
    groups:
      everything:
        patterns:
          - "*"
  - package-ecosystem: npm
    target-branch: develop
    directory: "/"
    ignore:
      - dependency-name: "@types/node" # Needs to be oldest LTS version
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
