module.exports = {
  cache: require('./cache'),
  cors: require('./cors'),
  dbManager: require('./dbManager'),
  doNotWaitForEmptyEventLoop: require('./doNotWaitForEmptyEventLoop'),
  functionShield: require('./functionShield'),
  httpContentNegotiation: require('./httpContentNegotiation'),
  httpErrorHandler: require('./httpErrorHandler'),
  httpEventNormalizer: require('./httpEventNormalizer'),
  httpHeaderNormalizer: require('./httpHeaderNormalizer'),
  httpPartialResponse: require('./httpPartialResponse'),
  httpSecurityHeaders: require('./httpSecurityHeaders'),
  jsonBodyParser: require('./jsonBodyParser'),
  s3KeyNormalizer: require('./s3KeyNormalizer'),
  secretsManager: require('./secretsManager'),
  ssm: require('./ssm'),
  urlEncodeBodyParser: require('./urlEncodeBodyParser'),
  validator: require('./validator'),
  warmup: require('./warmup')
}
