<script>
import LayoutAsideNav from "@design-system/svelte/LayoutAsideNav.svelte";
import { page } from "$app/state";

const { params, data, form } = page;

const nav = {
	"Intro to Middy": {
		Introduction: "/docs",
		"Getting Started": "/docs/intro/getting-started",
		"How It Works": "/docs/intro/how-it-works",
		"Early Response": "/docs/intro/early-interrupt",
		"Handling Errors": "/docs/intro/handling-errors",
		"Durable Functions": "/docs/intro/durable-functions",
		"Streamify Response": "/docs/intro/streamify-response",
		Testing: "/docs/intro/testing",
		"Use with TypeScript": "/docs/intro/typescript",
		Hooks: "/docs/intro/hooks",
		History: "/docs/intro/history",
		Influence: "/docs/intro/influence",
		Utilities: "/docs/intro/utilities",
		"Release Cycle": "/docs/intro/release-cycle",
		Contributing: "/docs/intro/contributing",
		Sponsoring: "/docs/intro/sponsoring",
	},
	Middlewares: {
		"Official Middlewares": "/docs/middlewares/intro",
		"Third-party Middlewares": "/docs/middlewares/third-party",
		appconfig: "/docs/middlewares/appconfig",
		"cloudformation-response": "/docs/middlewares/cloudformation-response",
		"cloudwatch-metrics": "/docs/middlewares/cloudwatch-metrics",
		"do-not-wait-for-empty-event-loop":
			"/docs/middlewares/do-not-wait-for-empty-event-loop",
		dynamodb: "/docs/middlewares/dynamodb",
		"error-logger": "/docs/middlewares/error-logger",
		"event-normalizer": "/docs/middlewares/event-normalizer",
		"http-content-encoding": "/docs/middlewares/http-content-encoding",
		"http-content-negotiation": "/docs/middlewares/http-content-negotiation",
		"http-cors": "/docs/middlewares/http-cors",
		"http-error-handler": "/docs/middlewares/http-error-handler",
		"http-event-normalizer": "/docs/middlewares/http-event-normalizer",
		"http-header-normalizer": "/docs/middlewares/http-header-normalizer",
		"http-json-body-parser": "/docs/middlewares/http-json-body-parser",
		"http-multipart-body-parser":
			"/docs/middlewares/http-multipart-body-parser",
		"http-partial-response": "/docs/middlewares/http-partial-response",
		"http-response-serializer": "/docs/middlewares/http-response-serializer",
		"http-security-headers": "/docs/middlewares/http-security-headers",
		"http-urlencode-body-parser":
			"/docs/middlewares/http-urlencode-body-parser",
		"http-urlencode-path-parser":
			"/docs/middlewares/http-urlencode-path-parser",
		"input-output-logger": "/docs/middlewares/input-output-logger",
		"rds-signer": "/docs/middlewares/rds-signer",
		s3: "/docs/middlewares/s3",
		"s3-object-response": "/docs/middlewares/s3-object-response",
		"secrets-manager": "/docs/middlewares/secrets-manager",
		"service-discovery": "/docs/middlewares/service-discovery",
		"sqs-partial-batch-failure": "/docs/middlewares/sqs-partial-batch-failure",
		ssm: "/docs/middlewares/ssm",
		sts: "/docs/middlewares/sts",
		validator: "/docs/middlewares/validator",
		warmup: "/docs/middlewares/warmup",
		"ws-json-body-parser": "/docs/middlewares/ws-json-body-parser",
		"ws-response": "/docs/middlewares/ws-response",
	},
	"Writing middlewares": {
		"Custom Middlewares": "/docs/writing-middlewares/intro",
		"Configurable Middlewares":
			"/docs/writing-middlewares/configurable-middlewares",
		"Inline Middlewares": "/docs/writing-middlewares/inline-middlewares",
		"Internal Storage": "/docs/writing-middlewares/internal-storage",
		"Handle Timeouts": "/docs/writing-middlewares/timeouts",
		"More Examples": "/docs/writing-middlewares/more-examples",
		"With TypeScript": "/docs/writing-middlewares/with-typescript",
	},
	Routers: {
		"cloudformation-router": "/docs/routers/cloudformation-router",
		"http-router": "/docs/routers/http-router",
		"ws-router": "/docs/routers/ws-router",
	},
	Upgrade: {
		"Upgrade 6.x -> 7.x": "/docs/upgrade/6-7",
		"Upgrade 5.x -> 6.x": "/docs/upgrade/5-6",
		"Upgrade 4.x -> 5.x": "/docs/upgrade/4-5",
		"Upgrade 3.x -> 4.x": "/docs/upgrade/3-4",
		"Upgrade 2.x -> 3.x": "/docs/upgrade/2-3",
		"Upgrade 1.x -> 2.x": "/docs/upgrade/1-2",
		"Upgrade 0.x -> 1.x": "/docs/upgrade/0-1",
	},
	"AWS event examples": {
		"All AWS Events": "/docs/events/intro",
		Alexa: "/docs/events/alexa",
		"API Gateway Authorizer": "/docs/events/api-gateway-authorizer",
		"API Gateway (HTTP)": "/docs/events/api-gateway-http",
		"API Gateway (REST)": "/docs/events/api-gateway-rest",
		"API Gateway (WebSocket)": "/docs/events/api-gateway-ws",
		"Application Load Balancer": "/docs/events/application-load-balancer",
		AppSync: "/docs/events/appsync",
		CloudFormation: "/docs/events/cloud-formation",
		"CloudFront Lambda@Edge": "/docs/events/cloud-front",
		CloudTrail: "/docs/events/cloud-trail",
		"CloudWatch Alarm": "/docs/events/cloud-watch-alarm",
		"CloudWatch Logs": "/docs/events/cloud-watch-logs",
		"Code Commit": "/docs/events/code-commit",
		CodePipeline: "/docs/events/code-pipeline",
		Cognito: "/docs/events/cognito",
		Config: "/docs/events/config",
		Connect: "/docs/events/connect",
		DocumentDB: "/docs/events/documentdb",
		DynamoDB: "/docs/events/dynamodb",
		EC2: "/docs/events/ec2",
		EventBridge: "/docs/events/event-bridge",
		"Function URL": "/docs/events/function-url",
		"Internet of Things (IoT)": "/docs/events/iot",
		"IoT Events": "/docs/events/iot-events",
		"Kafka, Managed Streaming (MSK)": "/docs/events/kafka-managed-streaming",
		"Kafka, Self-Managed": "/docs/events/kafka-self-managed",
		"Kinesis Firehose": "/docs/events/kinesis-firehose",
		"Kinesis Streams": "/docs/events/kinesis-streams",
		Lex: "/docs/events/lex",
		MQ: "/docs/events/mq",
		RDS: "/docs/events/rds",
		S3: "/docs/events/s3",
		"S3 Batch": "/docs/events/s3-batch",
		"S3 Object": "/docs/events/s3-object",
		"Secrets Manager": "/docs/events/secrets-manager",
		SES: "/docs/events/ses",
		SNS: "/docs/events/sns",
		SQS: "/docs/events/sqs",
		"VPC Lattice": "/docs/events/vpc-lattice",
		WorkMail: "/docs/events/workmail",
	},
	Integrations: {
		Intro: "/docs/integrations/intro",
		"AWS RDS": "/docs/integrations/RDS",
		"Apollo Server": "/docs/integrations/apollo-server",
		"Powertools for AWS Lambda": "/docs/integrations/lambda-powertools",
		Pino: "/docs/integrations/pino",
		"Serverless Framework": "/docs/integrations/serverless-framework",
		"Serverless Stack": "/docs/integrations/serverless-stack",
	},
	"Best practice": {
		Intro: "/docs/best-practices/intro",
		"Connection Reuse": "/docs/best-practices/connection-reuse",
		"Internal Context": "/docs/best-practices/internal-context",
		"Bundling Lambda Packages": "/docs/best-practices/bundling",
		"Small node_modules": "/docs/best-practices/small-node-modules",
		Profiling: "/docs/best-practices/profiling",
	},
	FAQ: "/docs/faq",
};
</script>

<LayoutAsideNav {nav} />
