#!/usr/bin/env sh
# ./.github/workflows/esmbuild {package}

cd packages/$1

mkdir -p dist

cp index.js dist/
cp index.d.ts dist/
cp index.js dist/inde.mjs
cp index.js dist/index.cjs

# convert ems to commonjs
sed -i '' 's/export default/module.exports =/g' dist/index.cjs
sed -i '' 's/export const /module.exports./g' dist/index.cjs