name: Tests (dco)

on:
  pull_request:

permissions:
  contents: read

jobs:
  dco:
    name: Tests (dco)
    runs-on: ubuntu-latest
    steps:
      - name: Check for Developer Certificate of Origin (DCO) compiance
        uses: KineticCafe/actions-dco@f7fe2fdfb5808e2528042be3919b67079100b96b # v3.0.0
